version: '3.8'

services:
  api:
    build: .
    container_name: todo-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/todos
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: todo-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=todos

volumes:
  mongo-data:
